import { WorldLocation, WorldNpc, WorldObject } from './worldTypes';

export const WORLD_WIDTH = 2200;
export const WORLD_HEIGHT = 1600;
export const PLAYER_WORLD_SIZE = 54;
export const PLAYER_WORLD_SPEED = 210;
export const PLAYER_HOUSE_SPAWN = { x: 1060, y: 875 };

export const worldLocations: WorldLocation[] = [
  {
    id: 'playerHouse',
    name: 'Player House',
    theme: 'Luxury mansion safe zone',
    x: 990,
    y: 690,
    width: 220,
    height: 170,
    color: '#50305d',
    accent: '#ffbf3f',
    enterable: true,
    interaction: 'Enter house, rest, save, plan missions',
    interiorTitle: 'Player House',
    interiorDescription: 'Safe mansion base with garden paths, driveway, planning table, and Boss meeting space.',
  },
  {
    id: 'boatingDock',
    name: 'Boating / Ship Riding Place',
    theme: 'Lake dock and ticket counter',
    x: 118,
    y: 280,
    width: 260,
    height: 190,
    color: '#15577a',
    accent: '#7de8ff',
    enterable: true,
    interaction: 'Ride boat / start ship travel',
    interiorTitle: 'Boating Dock',
    interiorDescription: 'Dock, benches, lamps, boats, ticket counter, and ship mission pickup.',
  },
  {
    id: 'magicCity',
    name: 'Magic City',
    theme: 'Amusement rides and crowds',
    x: 650,
    y: 150,
    width: 290,
    height: 210,
    color: '#5c238b',
    accent: '#ff61d8',
    enterable: true,
    interaction: 'Enter rides and meet crowd NPCs',
    interiorTitle: 'Magic City',
    interiorDescription: 'Playable amusement zone with colorful rides, crowds, paths, and mission stunts.',
  },
  {
    id: 'partyPartyYeah',
    name: 'Party Party Yeah',
    theme: 'Nightclub, VIP area, dancers',
    x: 1280,
    y: 118,
    width: 330,
    height: 230,
    color: '#5e123f',
    accent: '#ff2e8a',
    enterable: true,
    interaction: 'Enter club, talk, watch dancers, start bar missions',
    interiorTitle: 'Party Party Yeah',
    interiorDescription: 'Neon club interior with stage dancers, VIP boss seating, tables, crowd NPCs, and mission meetings.',
  },
  {
    id: 'policeStation',
    name: 'Police Station',
    theme: 'Restricted checkpoint',
    x: 1750,
    y: 220,
    width: 260,
    height: 190,
    color: '#1b426f',
    accent: '#ff3030',
    enterable: false,
    restricted: true,
    interaction: 'Restricted: only enter if caught by police',
    interiorTitle: 'Police Station',
    interiorDescription: 'Checkpoint, police jeep, whistle officer, holding room. Locked unless captured.',
  },
  {
    id: 'raniRajMahal',
    name: 'Rani-Raj Mahal',
    theme: 'Grand palace',
    x: 1420,
    y: 570,
    width: 330,
    height: 230,
    color: '#8b6230',
    accent: '#ffe08a',
    enterable: true,
    interaction: 'Enter guarded mahal',
    interiorTitle: 'Rani-Raj Mahal',
    interiorDescription: 'Grand palace interior with elegant walkways, guards, and elite mission rooms.',
  },
  {
    id: 'friendsHouse',
    name: 'Friends House',
    theme: 'Arion Vale strategy house',
    x: 520,
    y: 640,
    width: 230,
    height: 165,
    color: '#2b5f64',
    accent: '#a8fff1',
    enterable: true,
    interaction: 'Talk to Arion Vale',
    interiorTitle: 'Friends House',
    interiorDescription: 'Arion Vale waits in a living room discussion area while the Boss sits nearby.',
  },
  {
    id: 'pinkPalace',
    name: 'Pink Palace',
    theme: 'Guarded luxury palace',
    x: 1580,
    y: 1000,
    width: 300,
    height: 210,
    color: '#8f2e73',
    accent: '#ff9cdf',
    enterable: true,
    interaction: 'Enter guarded palace',
    interiorTitle: 'Pink Palace',
    interiorDescription: 'Luxury palace garden, security posts, and guarded mission chambers.',
  },
  {
    id: 'airport',
    name: 'Airport / Aeroplane Area',
    theme: 'Terminal, runway, hangar',
    x: 220,
    y: 980,
    width: 360,
    height: 250,
    color: '#2d536d',
    accent: '#b6e9ff',
    enterable: true,
    interaction: 'Sit in plane, travel, parachute jump',
    interiorTitle: 'Airport',
    interiorDescription: 'Terminal, runway, hangar, enterable aeroplane seats, world travel, and parachute landing selection.',
  },
  {
    id: 'clockTower',
    name: 'Clock Tower',
    theme: 'City landmark crossing',
    x: 930,
    y: 1110,
    width: 240,
    height: 210,
    color: '#514461',
    accent: '#f5d37f',
    enterable: true,
    interaction: 'Explore tower and crossing',
    interiorTitle: 'Clock Tower',
    interiorDescription: 'Tall landmark with crossing, guard posts, and exploration floors.',
  },
  {
    id: 'desert',
    name: 'Desert',
    theme: 'Large sand zone and oasis',
    x: 1710,
    y: 1320,
    width: 420,
    height: 230,
    color: '#9e6b2e',
    accent: '#ffe1a3',
    enterable: true,
    interaction: 'Ride camel and explore oasis',
    interiorTitle: 'Desert',
    interiorDescription: 'Wide sand routes, camel riding, exploration paths, and a small oasis deep inside the desert.',
  },
  {
    id: 'garage',
    name: 'Garage',
    theme: 'Vehicle hub',
    x: 790,
    y: 500,
    width: 210,
    height: 150,
    color: '#464b57',
    accent: '#ffbc35',
    enterable: true,
    interaction: 'Drive cars, SUVs, bikes, bicycles',
    interiorTitle: 'Garage',
    interiorDescription: 'Vehicle selection hub with cars, bicycles, armored SUVs, and a drivable test lane.',
  },
  {
    id: 'roseTemple',
    name: 'Rose Temple',
    theme: 'Temple grounds',
    x: 1120,
    y: 1220,
    width: 260,
    height: 190,
    color: '#7c3554',
    accent: '#ffb6cb',
    enterable: true,
    interaction: 'Enter temple grounds',
    interiorTitle: 'Rose Temple',
    interiorDescription: 'Atmospheric temple with rose paths, guards, lamp posts, and mission shrines.',
  },
  {
    id: 'garden',
    name: 'Garden',
    theme: 'Large open garden',
    x: 790,
    y: 870,
    width: 270,
    height: 190,
    color: '#236545',
    accent: '#95ff9b',
    enterable: true,
    interaction: 'Walk garden paths and lake',
    interiorTitle: 'Garden',
    interiorDescription: 'Large decorative garden with flower paths, art centerpiece, lake edge, and security patrols.',
  },
  {
    id: 'doorway',
    name: 'Doorway',
    theme: 'Grand ceremonial arch',
    x: 1370,
    y: 865,
    width: 240,
    height: 170,
    color: '#5b435f',
    accent: '#ffd36a',
    enterable: true,
    interaction: 'Pass through guarded arch',
    interiorTitle: 'Doorway',
    interiorDescription: 'Grand archway with guards, lamps, road access, and pass-through mission triggers.',
  },
];

export const worldObjects: WorldObject[] = [
  { id: 'road-main-x', label: 'Central east-west road', kind: 'road', x: 80, y: 785, width: 2040, height: 90, color: '#2c2f38' },
  { id: 'road-main-y', label: 'Central north-south road', kind: 'road', x: 1055, y: 110, width: 90, height: 1370, color: '#2c2f38' },
  { id: 'road-nw', label: 'Northwest road', kind: 'road', x: 345, y: 395, width: 760, height: 66, color: '#30323d' },
  { id: 'road-ne', label: 'Northeast road', kind: 'road', x: 1140, y: 365, width: 730, height: 66, color: '#30323d' },
  { id: 'road-sw', label: 'Airport road', kind: 'road', x: 400, y: 910, width: 710, height: 66, color: '#30323d' },
  { id: 'road-se', label: 'Palace road', kind: 'road', x: 1130, y: 1035, width: 770, height: 66, color: '#30323d' },
  { id: 'footpath-main-x-top', label: 'Footpath', kind: 'footpath', x: 80, y: 760, width: 2040, height: 22, color: '#6c6473' },
  { id: 'footpath-main-x-bottom', label: 'Footpath', kind: 'footpath', x: 80, y: 878, width: 2040, height: 22, color: '#6c6473' },
  { id: 'lake', label: 'Lake', kind: 'water', x: 30, y: 210, width: 430, height: 320, color: '#0b4964', blocked: true },
  { id: 'desert-sand', label: 'Sand Route', kind: 'sand', x: 1640, y: 1250, width: 520, height: 330, color: '#7d5728' },
  { id: 'desert-oasis', label: 'Deep Oasis', kind: 'water', x: 1940, y: 1450, width: 110, height: 56, color: '#187f8d', blocked: true },
  { id: 'party-stage', label: 'Dance Stage', kind: 'stage', x: 1370, y: 155, width: 145, height: 46, color: '#ff2e8a' },
  { id: 'airport-runway', label: 'Runway', kind: 'road', x: 210, y: 1260, width: 530, height: 55, color: '#202833' },
  { id: 'garage-lot', label: 'Vehicle Lot', kind: 'vehicle', x: 780, y: 455, width: 240, height: 62, color: '#2b2d34' },
  { id: 'garden-lake', label: 'Garden Lake', kind: 'water', x: 850, y: 960, width: 105, height: 55, color: '#1c6b74', blocked: true },
];

export const worldNpcs: WorldNpc[] = [
  { id: 'arion', name: 'Arion Vale', characterId: 'friend', role: 'friend', x: 610, y: 720, patrol: [{ x: 610, y: 720 }, { x: 690, y: 720 }], speed: 72, direction: 'right' },
  { id: 'police-whistle', name: 'Whistle Officer', characterId: 'police', role: 'police', x: 1710, y: 450, patrol: [{ x: 1710, y: 450 }, { x: 1910, y: 450 }], speed: 86, direction: 'right' },
  { id: 'guard-mahal', name: 'Mahal Guard', characterId: 'securityGuard1', role: 'guard', x: 1390, y: 820, patrol: [{ x: 1390, y: 820 }, { x: 1730, y: 820 }], speed: 78, direction: 'right' },
  { id: 'guard-temple', name: 'Temple Guard', characterId: 'securityGuard2', role: 'guard', x: 1120, y: 1170, patrol: [{ x: 1120, y: 1170 }, { x: 1360, y: 1170 }], speed: 78, direction: 'right' },
  { id: 'npc-woman-1', name: 'City Walker', characterId: 'npcWoman', role: 'civilian', x: 820, y: 760, patrol: [{ x: 820, y: 760 }, { x: 1240, y: 760 }], speed: 70, direction: 'right' },
  { id: 'npc-man-1', name: 'Shop Visitor', characterId: 'npcMan', role: 'civilian', x: 380, y: 900, patrol: [{ x: 380, y: 900 }, { x: 720, y: 900 }], speed: 68, direction: 'right' },
  { id: 'dancer-pink', name: 'Pink Couple Dancer', characterId: 'pinkCoupleDancers', role: 'dancer', x: 1340, y: 210, patrol: [{ x: 1340, y: 210 }, { x: 1370, y: 210 }], speed: 42, direction: 'right' },
  { id: 'dancer-purple', name: 'Purple Couple Dancer', characterId: 'purpleCoupleDance', role: 'dancer', x: 1440, y: 210, patrol: [{ x: 1440, y: 210 }, { x: 1480, y: 210 }], speed: 42, direction: 'right' },
  { id: 'dancer-green', name: 'Green Solo Dancer', characterId: 'centerDancer', role: 'dancer', x: 1530, y: 210, patrol: [{ x: 1530, y: 210 }, { x: 1560, y: 210 }], speed: 42, direction: 'right' },
];
