import { worldRoadObjects } from '../data/worldRoads';
import { WorldLocation, WorldNpc, WorldObject } from './worldTypes';

export const WORLD_WIDTH = 5200;
export const WORLD_HEIGHT = 9000;
export const PLAYER_WORLD_SIZE = 54;
export const PLAYER_WORLD_SPEED = 210;
export const PLAYER_HOUSE_SPAWN = { x: 2420, y: 1905 };

export const worldLocations: WorldLocation[] = [
  {
    id: 'playerHouse',
    name: 'Player House',
    theme: 'Luxury mansion safe zone',
    x: 2340,
    y: 1700,
    width: 220,
    height: 170,
    color: '#50305d',
    accent: '#ffbf3f',
    enterable: true,
    interaction: 'Enter house, rest, save, plan missions',
    interiorTitle: 'Player House',
    interiorDescription: 'Safe mansion base with garden paths, driveway, planning table, and Boss meeting space.',
  },
  {
    id: 'boatingDock',
    name: 'Boating / Ship Riding Place',
    theme: 'Lake dock and ticket counter',
    x: 250,
    y: 350,
    width: 260,
    height: 190,
    color: '#15577a',
    accent: '#7de8ff',
    enterable: true,
    interaction: 'Ride boat / start ship travel',
    interiorTitle: 'Boating Dock',
    interiorDescription: 'Dock, benches, lamps, boats, ticket counter, and ship mission pickup.',
  },
  {
    id: 'magicCity',
    name: 'Magic City',
    theme: 'Amusement rides and crowds',
    x: 1560,
    y: 310,
    width: 290,
    height: 210,
    color: '#5c238b',
    accent: '#ff61d8',
    enterable: true,
    interaction: 'Enter rides and meet crowd NPCs',
    interiorTitle: 'Magic City',
    interiorDescription: 'Playable amusement zone with colorful rides, crowds, paths, and mission stunts.',
  },
  {
    id: 'partyPartyYeah',
    name: 'Party Party Yeah',
    theme: 'Nightclub, VIP area, dancers',
    x: 3350,
    y: 320,
    width: 330,
    height: 230,
    color: '#5e123f',
    accent: '#ff2e8a',
    enterable: true,
    interaction: 'Enter club, talk, watch dancers, start bar missions',
    interiorTitle: 'Party Party Yeah',
    interiorDescription: 'Neon club interior with stage dancers, VIP boss seating, tables, crowd NPCs, and mission meetings.',
  },
  {
    id: 'policeStation',
    name: 'Police Station',
    theme: 'Restricted checkpoint',
    x: 4650,
    y: 560,
    width: 260,
    height: 190,
    color: '#1b426f',
    accent: '#ff3030',
    enterable: false,
    restricted: true,
    interaction: 'Restricted: only enter if caught by police',
    interiorTitle: 'Police Station',
    interiorDescription: 'Checkpoint, police jeep, whistle officer, holding room. Locked unless captured.',
  },
  {
    id: 'raniRajMahal',
    name: 'Rani-Raj Mahal',
    theme: 'Grand palace',
    x: 3800,
    y: 1450,
    width: 330,
    height: 230,
    color: '#8b6230',
    accent: '#ffe08a',
    enterable: true,
    interaction: 'Enter guarded mahal',
    interiorTitle: 'Rani-Raj Mahal',
    interiorDescription: 'Grand palace interior with elegant walkways, guards, and elite mission rooms.',
  },
  {
    id: 'friendsHouse',
    name: 'Friends House',
    theme: 'Arion Vale strategy house',
    x: 1375,
    y: 1450,
    width: 230,
    height: 165,
    color: '#2b5f64',
    accent: '#a8fff1',
    enterable: true,
    interaction: 'Talk to Arion Vale',
    interiorTitle: 'Friends House',
    interiorDescription: 'Arion Vale waits in a living room discussion area while the Boss sits nearby.',
  },
  {
    id: 'pinkPalace',
    name: 'Pink Palace',
    theme: 'Guarded luxury palace',
    x: 4200,
    y: 2550,
    width: 300,
    height: 210,
    color: '#8f2e73',
    accent: '#ff9cdf',
    enterable: true,
    interaction: 'Enter guarded palace',
    interiorTitle: 'Pink Palace',
    interiorDescription: 'Luxury palace garden, security posts, and guarded mission chambers.',
  },
  {
    id: 'airport',
    name: 'Airport / Aeroplane Area',
    theme: 'Terminal, runway, hangar',
    x: 350,
    y: 2850,
    width: 360,
    height: 250,
    color: '#2d536d',
    accent: '#b6e9ff',
    enterable: true,
    interaction: 'Sit in plane, travel, parachute jump',
    interiorTitle: 'Airport',
    interiorDescription: 'Terminal, runway, hangar, enterable aeroplane seats, world travel, and parachute landing selection.',
  },
  {
    id: 'clockTower',
    name: 'Clock Tower',
    theme: 'City landmark crossing',
    x: 2450,
    y: 3100,
    width: 240,
    height: 210,
    color: '#514461',
    accent: '#f5d37f',
    enterable: true,
    interaction: 'Explore tower and crossing',
    interiorTitle: 'Clock Tower',
    interiorDescription: 'Tall landmark with crossing, guard posts, and exploration floors.',
  },
  {
    id: 'desert',
    name: 'Desert',
    theme: 'Large sand zone and oasis',
    x: 4350,
    y: 3350,
    width: 520,
    height: 250,
    color: '#9e6b2e',
    accent: '#ffe1a3',
    enterable: true,
    interaction: 'Ride camel and explore oasis',
    interiorTitle: 'Desert',
    interiorDescription: 'Wide sand routes, camel riding, exploration paths, and a small oasis deep inside the desert.',
  },
  {
    id: 'garage',
    name: 'Garage',
    theme: 'Vehicle hub',
    x: 2200,
    y: 980,
    width: 210,
    height: 150,
    color: '#464b57',
    accent: '#ffbc35',
    enterable: true,
    interaction: 'Drive cars, SUVs, bikes, bicycles',
    interiorTitle: 'Garage',
    interiorDescription: 'Vehicle selection hub with cars, bicycles, armored SUVs, and a drivable test lane.',
  },
  {
    id: 'roseTemple',
    name: 'Rose Temple',
    theme: 'Temple grounds',
    x: 3150,
    y: 3250,
    width: 260,
    height: 190,
    color: '#7c3554',
    accent: '#ffb6cb',
    enterable: true,
    interaction: 'Enter temple grounds',
    interiorTitle: 'Rose Temple',
    interiorDescription: 'Atmospheric temple with rose paths, guards, lamp posts, and mission shrines.',
  },
  {
    id: 'garden',
    name: 'Garden',
    theme: 'Large open garden',
    x: 2350,
    y: 2200,
    width: 270,
    height: 190,
    color: '#236545',
    accent: '#95ff9b',
    enterable: true,
    interaction: 'Walk garden paths and lake',
    interiorTitle: 'Garden',
    interiorDescription: 'Large decorative garden with flower paths, art centerpiece, lake edge, and security patrols.',
  },
  {
    id: 'doorway',
    name: 'Doorway',
    theme: 'Grand ceremonial arch',
    x: 3450,
    y: 2250,
    width: 240,
    height: 170,
    color: '#5b435f',
    accent: '#ffd36a',
    enterable: true,
    interaction: 'Pass through guarded arch',
    interiorTitle: 'Doorway',
    interiorDescription: 'Grand archway with guards, lamps, road access, and pass-through mission triggers.',
  },
];

export const worldObjects: WorldObject[] = [
  ...worldRoadObjects,
  { id: 'great-west-sea', label: 'Great West Sea', kind: 'water', x: 40, y: 620, width: 1260, height: 8120, color: '#087ca4', blocked: true },
  { id: 'lake', label: 'Boating Bay', kind: 'water', x: 120, y: 280, width: 760, height: 510, color: '#0b4964', blocked: true },
  { id: 'sea-island-1', label: 'Palm Island', kind: 'sand', x: 250, y: 1420, width: 210, height: 140, color: '#b88945', blocked: true },
  { id: 'sea-island-2', label: 'Rock Island', kind: 'sand', x: 790, y: 2380, width: 230, height: 150, color: '#8b764f', blocked: true },
  { id: 'sea-island-3', label: 'Tiny Resort Island', kind: 'grass', x: 360, y: 3820, width: 260, height: 170, color: '#2d7c3d', blocked: true },
  { id: 'sea-island-4', label: 'Far Palm Island', kind: 'sand', x: 760, y: 5650, width: 280, height: 180, color: '#bd9250', blocked: true },
  { id: 'sea-island-5', label: 'End Sea Island', kind: 'grass', x: 260, y: 7600, width: 320, height: 220, color: '#337d40', blocked: true },
  { id: 'desert-sand', label: 'Sand Route', kind: 'sand', x: 4180, y: 3200, width: 920, height: 560, color: '#7d5728' },
  { id: 'desert-oasis', label: 'Deep Oasis', kind: 'water', x: 4860, y: 3540, width: 180, height: 86, color: '#187f8d', blocked: true },
  { id: 'party-stage', label: 'Dance Stage', kind: 'stage', x: 3468, y: 360, width: 190, height: 60, color: '#ff2e8a' },
  { id: 'airport-runway', label: 'Runway', kind: 'road', x: 300, y: 3160, width: 930, height: 70, color: '#202833' },
  { id: 'garage-lot', label: 'Vehicle Lot', kind: 'vehicle', x: 2180, y: 920, width: 300, height: 74, color: '#2b2d34' },
  { id: 'garden-lake', label: 'Garden Lake', kind: 'water', x: 2440, y: 2300, width: 172, height: 86, color: '#1c6b74', blocked: true },
];

export const worldNpcs: WorldNpc[] = [
  { id: 'arion', name: 'Arion Vale', characterId: 'friend', role: 'friend', x: 1500, y: 1610, patrol: [{ x: 1500, y: 1610 }, { x: 1630, y: 1610 }], speed: 72, direction: 'right' },
  { id: 'police-whistle', name: 'Whistle Officer', characterId: 'police', role: 'police', x: 4580, y: 820, patrol: [{ x: 4580, y: 820 }, { x: 4920, y: 820 }], speed: 86, direction: 'right' },
  { id: 'guard-mahal', name: 'Mahal Guard', characterId: 'securityGuard1', role: 'guard', x: 3760, y: 1700, patrol: [{ x: 3760, y: 1700 }, { x: 4100, y: 1700 }], speed: 78, direction: 'right' },
  { id: 'guard-temple', name: 'Temple Guard', characterId: 'securityGuard2', role: 'guard', x: 3130, y: 3190, patrol: [{ x: 3130, y: 3190 }, { x: 3440, y: 3190 }], speed: 78, direction: 'right' },
  { id: 'npc-woman-1', name: 'City Walker', characterId: 'npcWoman', role: 'civilian', x: 2140, y: 1880, patrol: [{ x: 2140, y: 1880 }, { x: 2780, y: 1880 }], speed: 70, direction: 'right' },
  { id: 'npc-man-1', name: 'Shop Visitor', characterId: 'npcMan', role: 'civilian', x: 690, y: 2920, patrol: [{ x: 690, y: 2920 }, { x: 1210, y: 2920 }], speed: 68, direction: 'right' },
  { id: 'dancer-pink', name: 'Pink Couple Dancer', characterId: 'pinkCoupleDancers', role: 'dancer', x: 3410, y: 392, patrol: [{ x: 3410, y: 392 }, { x: 3460, y: 392 }], speed: 42, direction: 'right' },
  { id: 'dancer-purple', name: 'Purple Couple Dancer', characterId: 'purpleCoupleDance', role: 'dancer', x: 3530, y: 392, patrol: [{ x: 3530, y: 392 }, { x: 3580, y: 392 }], speed: 42, direction: 'right' },
  { id: 'dancer-green', name: 'Green Solo Dancer', characterId: 'centerDancer', role: 'dancer', x: 3650, y: 392, patrol: [{ x: 3650, y: 392 }, { x: 3700, y: 392 }], speed: 42, direction: 'right' },
];
