import { worldRoadObjects } from '../data/worldRoads';
import { friendsHouseExterior } from '../data/friendsHouseExteriorConfig';
import { fillerDistrictObjects } from '../data/fillerDistricts';
import { WorldLocation, WorldNpc, WorldObject } from './worldTypes';

export const WORLD_WIDTH = 12000;
export const WORLD_HEIGHT = 8000;
export const PLAYER_WORLD_SIZE = 54;
export const PLAYER_WORLD_SPEED = 520;
export const PLAYER_HOUSE_SPAWN = { x: 5900, y: 3900 };

export const worldLocations: WorldLocation[] = [
  {
    id: 'playerHouse',
    name: 'Player House',
    theme: 'Luxury mansion safe zone',
    x: 5600,
    y: 3600,
    width: 900,
    height: 700,
    color: '#50305d',
    accent: '#ffbf3f',
    enterable: true,
    interaction: 'Enter house, rest, save, plan missions',
    interiorTitle: 'Player House',
    interiorDescription: 'Safe mansion base with garden paths, driveway, planning table, and Boss meeting space.',
  },
  {
    id: 'boatingDock',
    name: 'Boating / Ship Riding Place',
    theme: 'Lake dock and ticket counter',
    x: 900,
    y: 700,
    width: 1300,
    height: 900,
    color: '#15577a',
    accent: '#7de8ff',
    enterable: true,
    interaction: 'Ride boat / start ship travel',
    interiorTitle: 'Boating Dock',
    interiorDescription: 'Dock, benches, lamps, boats, ticket counter, and ship mission pickup.',
  },
  {
    id: 'magicCity',
    name: 'Magic City',
    theme: 'Amusement rides and crowds',
    x: 3300,
    y: 700,
    width: 1200,
    height: 900,
    color: '#5c238b',
    accent: '#ff61d8',
    enterable: true,
    interaction: 'Enter rides and meet crowd NPCs',
    interiorTitle: 'Magic City',
    interiorDescription: 'Playable amusement zone with colorful rides, crowds, paths, and mission stunts.',
  },
  {
    id: 'partyPartyYeah',
    name: 'Party Party Yeah',
    theme: 'Nightclub, VIP area, dancers',
    x: 5800,
    y: 700,
    width: 1200,
    height: 900,
    color: '#5e123f',
    accent: '#ff2e8a',
    enterable: true,
    interaction: 'Enter club, talk, watch dancers, start bar missions',
    interiorTitle: 'Party Party Yeah',
    interiorDescription: 'Neon club interior with stage dancers, VIP boss seating, tables, crowd NPCs, and mission meetings.',
  },
  {
    id: 'policeStation',
    name: 'Police Station',
    theme: 'Restricted checkpoint',
    x: 8400,
    y: 700,
    width: 1200,
    height: 900,
    color: '#1b426f',
    accent: '#ff3030',
    enterable: false,
    restricted: true,
    interaction: 'Restricted: only enter if caught by police',
    interiorTitle: 'Police Station',
    interiorDescription: 'Checkpoint, police jeep, whistle officer, holding room. Locked unless captured.',
  },
  {
    id: 'raniRajMahal',
    name: 'Rani-Raj Mahal',
    theme: 'Grand palace',
    x: 1200,
    y: 2700,
    width: 1300,
    height: 950,
    color: '#8b6230',
    accent: '#ffe08a',
    enterable: true,
    interaction: 'Enter guarded mahal',
    interiorTitle: 'Rani-Raj Mahal',
    interiorDescription: 'Grand palace interior with elegant walkways, guards, and elite mission rooms.',
  },
  {
    id: 'friendsHouse',
    name: 'Friends House',
    theme: 'Arion Vale strategy house',
    x: friendsHouseExterior.x,
    y: friendsHouseExterior.y,
    width: friendsHouseExterior.width,
    height: friendsHouseExterior.height,
    color: '#2b5f64',
    accent: '#a8fff1',
    enterable: true,
    interaction: 'Enter Friends House from the front door',
    interiorTitle: 'Friends House',
    interiorDescription: 'Arion Vale waits in a living room discussion area while the Boss sits nearby.',
  },
  {
    id: 'pinkPalace',
    name: 'Pink Palace',
    theme: 'Guarded luxury palace',
    x: 9900,
    y: 2800,
    width: 1400,
    height: 1000,
    color: '#8f2e73',
    accent: '#ff9cdf',
    enterable: true,
    interaction: 'Enter guarded palace',
    interiorTitle: 'Pink Palace',
    interiorDescription: 'Luxury palace garden, security posts, and guarded mission chambers.',
  },
  {
    id: 'airport',
    name: 'Airport / Aeroplane Area',
    theme: 'Terminal, runway, hangar',
    x: 700,
    y: 5200,
    width: 1700,
    height: 1000,
    color: '#2d536d',
    accent: '#b6e9ff',
    enterable: true,
    interaction: 'Sit in plane, travel, parachute jump',
    interiorTitle: 'Airport',
    interiorDescription: 'Terminal, runway, hangar, enterable aeroplane seats, world travel, and parachute landing selection.',
  },
  {
    id: 'clockTower',
    name: 'Clock Tower',
    theme: 'City landmark crossing',
    x: 7000,
    y: 5200,
    width: 1000,
    height: 900,
    color: '#514461',
    accent: '#f5d37f',
    enterable: true,
    interaction: 'Explore tower and crossing',
    interiorTitle: 'Clock Tower',
    interiorDescription: 'Tall landmark with crossing, guard posts, and exploration floors.',
  },
  {
    id: 'desert',
    name: 'Desert',
    theme: 'Large sand zone and oasis',
    x: 9300,
    y: 5000,
    width: 2300,
    height: 2200,
    color: '#9e6b2e',
    accent: '#ffe1a3',
    enterable: true,
    interaction: 'Ride camel and explore oasis',
    interiorTitle: 'Desert',
    interiorDescription: 'Wide sand routes, camel riding, exploration paths, and a small oasis deep inside the desert.',
  },
  {
    id: 'garage',
    name: 'Garage',
    theme: 'Vehicle hub',
    x: 900,
    y: 7000,
    width: 1200,
    height: 800,
    color: '#464b57',
    accent: '#ffbc35',
    enterable: true,
    interaction: 'Drive cars, SUVs, bikes, bicycles',
    interiorTitle: 'Garage',
    interiorDescription: 'Vehicle selection hub with cars, bicycles, armored SUVs, and a drivable test lane.',
  },
  {
    id: 'roseTemple',
    name: 'Rose Temple',
    theme: 'Temple grounds',
    x: 3300,
    y: 6900,
    width: 1200,
    height: 850,
    color: '#7c3554',
    accent: '#ffb6cb',
    enterable: true,
    interaction: 'Enter temple grounds',
    interiorTitle: 'Rose Temple',
    interiorDescription: 'Atmospheric temple with rose paths, guards, lamp posts, and mission shrines.',
  },
  {
    id: 'garden',
    name: 'Garden',
    theme: 'Large open garden',
    x: 5700,
    y: 6900,
    width: 1300,
    height: 850,
    color: '#236545',
    accent: '#95ff9b',
    enterable: true,
    interaction: 'Walk garden paths and lake',
    interiorTitle: 'Garden',
    interiorDescription: 'Large decorative garden with flower paths, art centerpiece, lake edge, and security patrols.',
  },
  {
    id: 'doorway',
    name: 'Doorway',
    theme: 'Grand ceremonial arch',
    x: 8300,
    y: 6900,
    width: 1200,
    height: 850,
    color: '#5b435f',
    accent: '#ffd36a',
    enterable: true,
    interaction: 'Pass through guarded arch',
    interiorTitle: 'Doorway',
    interiorDescription: 'Grand archway with guards, lamps, road access, and pass-through mission triggers.',
  },
];

export const worldObjects: WorldObject[] = [
  ...worldRoadObjects,
  ...fillerDistrictObjects,
  // Sea + dock area around Boating Dock (900,700,1300,900), stretching south along the
  // west vertical road corridor so boats can travel toward Rani-Raj Mahal / Airport.
  { id: 'great-west-sea', label: 'Great West Sea', kind: 'water', x: 750, y: 1600, width: 900, height: 3600, color: '#087ca4', blocked: true },
  { id: 'lake', label: 'Boating Bay', kind: 'water', x: 900, y: 700, width: 1100, height: 850, color: '#0b4964', blocked: true },
  { id: 'sea-island-1', label: 'Palm Island', kind: 'sand', x: 1050, y: 1900, width: 210, height: 140, color: '#b88945', blocked: true },
  { id: 'desert-sand', label: 'Sand Route', kind: 'sand', x: 9300, y: 5000, width: 2300, height: 2200, color: '#7d5728' },
  { id: 'desert-oasis', label: 'Deep Oasis', kind: 'water', x: 10300, y: 5900, width: 300, height: 160, color: '#187f8d', blocked: true },
  { id: 'desert-oasis-2', label: 'Twin Oasis', kind: 'water', x: 10200, y: 6650, width: 260, height: 150, color: '#187f8d', blocked: true },
  { id: 'oasis-lake', label: 'Oasis Lake', kind: 'water', x: 9350, y: 7250, width: 420, height: 260, color: '#0e668a', blocked: true },
  { id: 'party-stage', label: 'Dance Stage', kind: 'stage', x: 6250, y: 900, width: 190, height: 60, color: '#ff2e8a' },
  { id: 'airport-runway', label: 'Runway', kind: 'road', x: 750, y: 5850, width: 1400, height: 90, color: '#202833' },
  { id: 'garage-lot', label: 'Vehicle Lot', kind: 'vehicle', x: 1000, y: 7350, width: 300, height: 74, color: '#2b2d34' },
  { id: 'garden-lake', label: 'Garden Pool', kind: 'water', x: 5850, y: 7350, width: 520, height: 180, color: '#0e668a', blocked: true },
];

export const worldNpcs: WorldNpc[] = [
  { id: 'arion', name: 'Arion Vale', characterId: 'friend', role: 'friend', x: 8000, y: 3450, patrol: [{ x: 8000, y: 3450 }, { x: 8180, y: 3450 }], speed: 72, direction: 'right' },
  { id: 'police-whistle', name: 'Whistle Officer', characterId: 'police', role: 'police', x: 8500, y: 1150, patrol: [{ x: 8500, y: 1150 }, { x: 8900, y: 1150 }], speed: 86, direction: 'right' },
  { id: 'guard-mahal', name: 'Mahal Guard', characterId: 'securityGuard1', role: 'guard', x: 1400, y: 3100, patrol: [{ x: 1400, y: 3100 }, { x: 1800, y: 3100 }], speed: 78, direction: 'right' },
  { id: 'guard-temple', name: 'Temple Guard', characterId: 'securityGuard2', role: 'guard', x: 3400, y: 7300, patrol: [{ x: 3400, y: 7300 }, { x: 3780, y: 7300 }], speed: 78, direction: 'right' },
  { id: 'npc-woman-1', name: 'City Walker', characterId: 'npcWoman', role: 'civilian', x: 4200, y: 1200, patrol: [{ x: 4200, y: 1200 }, { x: 4900, y: 1200 }], speed: 70, direction: 'right' },
  { id: 'npc-man-1', name: 'Shop Visitor', characterId: 'npcMan', role: 'civilian', x: 1100, y: 7450, patrol: [{ x: 1100, y: 7450 }, { x: 1600, y: 7450 }], speed: 68, direction: 'right' },
  { id: 'dancer-pink', name: 'Pink Couple Dancer', characterId: 'pinkCoupleDancers', role: 'dancer', x: 6100, y: 940, patrol: [{ x: 6100, y: 940 }, { x: 6160, y: 940 }], speed: 42, direction: 'right' },
  { id: 'dancer-purple', name: 'Purple Couple Dancer', characterId: 'purpleCoupleDance', role: 'dancer', x: 6250, y: 940, patrol: [{ x: 6250, y: 940 }, { x: 6310, y: 940 }], speed: 42, direction: 'right' },
  { id: 'dancer-green', name: 'Green Solo Dancer', characterId: 'centerDancer', role: 'dancer', x: 6400, y: 940, patrol: [{ x: 6400, y: 940 }, { x: 6460, y: 940 }], speed: 42, direction: 'right' },
];
